### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by noobkiddie** [SusmithKrishnan/torghost#102]
![Screenshot_20201014_233418](https://user-images.githubusercontent.com/72414695/96077590-e15f1700-0e75-11eb-9793-55555902dfe0.png)

**Comment by RidelHI** [comment]
same for me

**Comment by lreading** [comment]
This may not be a best practice or a real solution, but it worked as a workaround for me.  Install the "packaging" dependency using sudo and the -H flag:
`sudo -H pip3 install packaging`

**Comment by noobkiddie** [comment]
It worked. Thanks bro
