### ISSUE TITLE
no internet connection upon start

### ISSUE THREAD

**Issue by lumberjack29** [SusmithKrishnan/torghost#27]
when I start torghost it fetches, and reads current ip is blank. and no internet connection at all. i stop torghost and it displays the proper IP and network is back.

**Comment by legentz** [comment]
Same here

**Comment by MazenElzanaty** [comment]
Same here

**Comment by Phil-ThePower-Pearce** [comment]
same.

**Comment by susmithHCK** [comment]
ping command wont work in torghost. Open a browser and goto check.torproject.org what does it show

**Comment by hax4hax** [comment]
Guys,If you use Kali Linux try with old version like 2017.02 works perfect.On new version have some issues.

**Comment by PixsaOJ** [comment]
Did anyone got a fix? Same issue on Ubuntu 18.04

**Comment by FryerTuck** [comment]
> Guys,If you use Kali Linux try with old version like 2017.02 works perfect.On new version have some issues.

uhuh

**Comment by SusmithKrishnan** [comment]
Check the latest version, see if it works. cheers!
