### ISSUE TITLE
Lock Problem

### ISSUE THREAD

**Issue by haruhiko156** [SusmithKrishnan/torghost#31]
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
every time i try to install torghost, this is what it says..plz help

**Comment by d4rk0wl** [comment]
Fresh install of Kali? Are you able to update apt?

If not, try `rm -rf /var/lib/dkpg/lock`
