### ISSUE TITLE
No module named stem

### ISSUE THREAD

**Issue by shuhrat02** [SusmithKrishnan/torghost#33]
HI guys!
have an issue when start torghost:

`torghost start
Traceback (most recent call last):
  File "/usr/bin/torghost", line 9, in <module>
    from stem import Signal
ImportError: No module named stem
`

how can I fix it?

**Comment by shuhrat02** [comment]
fixed by: " pip install stem "

tnx, close this issue

**Comment by adamrg73** [comment]
fixed by: " pip install stem "

tnx, close this issue

doesnt work
ubuntu 20.04
python3 or python2
