### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by RebiWeedman** [SusmithKrishnan/torghost#35]
Traceback (most recent call last):
File “/usr/bin/torghost”, line 183, in
start_torghost()
File “/usr/bin/torghost”, line 95, in start_torghost
if TorrcCfgString in open(Torrc).read():
IOError: [Errno 2] No such file or directory: ‘/etc/tor/torrc’

Please help

**Comment by SiNaPsEr0x** [comment]
when version of kali you use?

**Comment by tonymon7anna101** [comment]
i know how to solve the problem for the trace back error you have to type this in sudo apt-get install tor -y

and with ip error when it does not work if have to cep typing torghost start until it gives you a ip do it 15 times to see if that works

**Comment by SusmithKrishnan** [comment]
new install script works, please check the latest update
