### ISSUE TITLE
traceback error FIXED AND IP error

### ISSUE THREAD

**Issue by tonymon7anna101** [SusmithKrishnan/torghost#36]
i know how to solve the problem for the trace back error you have to type this in sudo apt-get install tor -y

and with ip error when it does not work if have to cep typing torghost start until it gives you a ip do it 15 times to see if that works

**Comment by tonymon7anna101** [comment]
leave a comment if your problem was fixed

**Comment by SusmithKrishnan** [comment]
I hope new update fixed it all
