### ISSUE TITLE
Can't stop/switch torghost

### ISSUE THREAD

**Issue by sergorl** [SusmithKrishnan/torghost#38]
Option stop and switch doesn't work! By the way after I run torghost I lose my internet connection!

**Comment by FryerTuck** [comment]
You need to install `network-manager`. 
After that make sure it's running; assuming you're using Kali:
```
    apt-get install network-manager
    systemctl enable network-manager
    susyemctl start network-manager
```

Then if torghost is running, kill it (by any means) .. then restart the `tor` service .. then `torghost start` 
... ya, I don't have a life ... sue me
