### ISSUE TITLE
pip install stem command not found in bash

### ISSUE THREAD

**Issue by JBoman** [SusmithKrishnan/torghost#39]

**Comment by JBoman** [comment]
as stated "pip install stem" fails in Debian 9 terminal. bash returns a "pip command not found". Need a different solution to install the missing stem module.

**Comment by Leetcore** [comment]
If you have installed Python 2.x correctly? Does "python -version" work?

**Comment by CrippledTable** [comment]
I tried downloading python 2 and 3. Neither installed pip. However, installing pip installed pip ;).

apt install pip
pip install stem

**Comment by kranercc** [comment]
you can fix the problem with
sudo apt-get install python3-pip 

Or
sudo apt-get install python2-pip.

i've made a pull request to fix a bug and maybe he  will also add this 2 commands in the script :laughing:

**Comment by SusmithKrishnan** [comment]
This is an issue with your particular system due to miss-configuration of python 2 and 3. I hope new update fixed it all
