### ISSUE TITLE
API integration issues

### ISSUE THREAD

**Issue by FryerTuck** [SusmithKrishnan/torghost#40]
I've written a wrapper that implements `torghost` as a `systemd` service and ... (sigh) .. `torghost` is very unstable; it breaks more often than it works. One would expect certain things to be simple; like if it's not running and you tell it to stop, it should just not do anything, maybe even `exit(0)` immediately .... but no, apparently it needs to hang indefinitely for some reason.

- when it's not running and you tell it to stop .. it hangs
- when it's running and you tell it to start .. it either starts (again) or .. hangs
- when it's running and you tell it to switch .. it either switches (in due time) or ..  hangs
- when it's not running and you tell it to switch .. it hangs
- when it's not running and you tell it to start, it either hangs or starts (in due time)

 .. we need to talk

**Comment by SusmithKrishnan** [comment]
Can you make a pull request
