### ISSUE TITLE
Error: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by omid3098** [SusmithKrishnan/torghost#52]
Installed tor.
Installed torghost.
Running command torghost -s will result:
[27338] Error loading Python lib '/usr/share/torghost/libpython2.7.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/torghost/libpython2.7.so.1.0)

I could not find the solution in previous issues.

**Comment by daveedave** [comment]
I get the same Issue. I am using Ubuntu 18.04

**Comment by SusmithKrishnan** [comment]
This is a dependency version issue. your GLIBC version may be greater than 2.29. Try compiling from the source. [Use build instructions](https://github.com/SusmithKrishnan/torghost#build-and-install-from-source)

**Comment by ragman105** [comment]
Hi,

Same Problem here with Debian Buster, same Problem with Build.sh script!

**Comment by und3fined404** [comment]
same issue

**Comment by I-RaFaEl-I** [comment]
same issue Ubuntu MATE 18.04 LTS

**Comment by AshleighD** [comment]
If you are on 18.04.3 LTS use this link it helped 

https://askubuntu.com/questions/1143268/how-to-install-a-libc6-version-2-29

**Comment by AshleighD** [comment]
> same issue Ubuntu MATE 18.04 LTS

except I'm now stuck where it's just saying current IP

**Comment by gmkbenjamin** [comment]
This commit fixes lib issue and stuck on current IP issue: 3d1541bd64fa58c72038e81ea895b9990adc4cb2

**Comment by AshleighD** [comment]
Can someone send me a compiled 3.0.3 .deb file?
