### ISSUE TITLE
arm64 not supported

### ISSUE THREAD

**Issue by r1l4r** [SusmithKrishnan/torghost#54]
dpkg: error processing archive torghost_3.0_amd64.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 torghost_3.0_amd64.deb
done

**Comment by SusmithKrishnan** [comment]
If you are using raspberry or similar arm devices, compile it from the source.

**Comment by TwiztedWisard** [comment]
Hi, when I try to compile from source I get the following error https://pastebin.com/m3yGLCfT
I can’t see an obvious reason but I’m fairly new to Kali, and Linux in general

**Comment by frayment** [comment]
@TwiztedWisard You should post the error log when it is run with `sudo` to see if the log is any different.

**Comment by TwiztedWisard** [comment]
Will do, got a few work commitments but it will hopefully be in the next 48hrs 🙂
