### ISSUE TITLE
[3644] Error loading Python lib

### ISSUE THREAD

**Issue by ipaidthebills** [SusmithKrishnan/torghost#59]
I've had torghost run 1 time without issue but now I get ;

[3644] Error loading Python lib '/usr/bin/libpython2.7.so.1.0': dlopen: /usr/bin/libpython2.7.so.1.0: cannot open shared object file: No such file or directory

I have also tried reinstalling using all 3 mothods provided. Any ideas what is wrong?

**Comment by snock** [comment]
same problem with the latest version of kali

**Comment by merkleID** [comment]
> `same problem with the latest version of kali` .
> 
> Although if I run it from /usr/share/torghost, if it works it works although it has several errors as it does not show the logo and fails when accessing the web to display the ip.

This happens to me either.
My small suggestion to torghost developer is to use a simple 'curl ifconfig.me' to retrieve current ip instead of current herokucdn 
(the error with ip retrieving is:
iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
)

**Comment by gmkbenjamin** [comment]
This PR fixes it: 923fdc07032089920b839ef29006b457435c2e5f

**Comment by SkyBoltDom** [comment]
or just use python3

**Comment by SusmithKrishnan** [comment]
Build tools updated in the latest version. Kali is using py 3 as default now.
