### ISSUE TITLE
Issue when Fetching current IP

### ISSUE THREAD

**Issue by KoZmicKali** [SusmithKrishnan/torghost#60]
torghost -s
[08:36:43] Always check for updates using -u option [08:36:44] Torrc file already configured
[08:36:44] Configuring DNS resolv.conf file..  [done]
[08:36:44] Stopping tor service  [done]
[08:36:44] Starting new tor daemon  [done]
[08:36:44] setting up iptables rules [done]
[08:36:44] Fetching current IP...
[08:36:44] CURRENT IP : <!DOCTYPE html>
        <html>
          <head>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta charset="utf-8">
                <title>Application Error</title>
                <style media="screen">
                  html,body,iframe {
                        margin: 0;
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;                                                                       
                        border: 0;                                                                          
                  }                                                                                         
                </style>                                                                                    
          </head>                                                                                           
          <body>                                                                                            
                <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>              
          </body>                                                                                           
        </html>                                      

Also after rebooting my OS I have no internet at all. (messed up my DNS?) I have to restart torghost just to get back online.

**Comment by gmkbenjamin** [comment]
Author's server seems to be down. Fixed in 3d1541bd64fa58c72038e81ea895b9990adc4cb2
