### ISSUE TITLE
libpython 2.7 and GLIBC 2.29

### ISSUE THREAD

**Issue by merkleID** [SusmithKrishnan/torghost#63]
Hi!
while torghost runs smoothly on Kali (except for the small ip retrieving problem), this is what happens on Ubuntu 18.04.4 server:

root@ubuntu:~/git/torghost# torghost -s
[31690] Error loading Python lib '/usr/share/torghost/libpython2.7.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/torghost/libpython2.7.so.1.0)

tried installing *.deb package but problem remains the same.
Thank-you!

**Comment by gmkbenjamin** [comment]
This is due to missing a specific version of GLIBC. 
Use the build.sh in 923fdc07032089920b839ef29006b457435c2e5f should work.

**Comment by merkleID** [comment]
> This is due to missing a specific version of GLIBC.
> Use the build.sh in [923fdc0](https://github.com/SusmithKrishnan/torghost/commit/923fdc07032089920b839ef29006b457435c2e5f) should work.

Hi.
Thank-you for your time.
I git fetched latest release.
It's now starting and the GLIBC problem seems solved, but it gets stucked this way:

root@ubuntu:~/git/torghost/dist# ./torghost -s
[14:59:57] Always check for updates using -u option [14:59:57] Torrc file already configured
[14:59:57] Configuring DNS resolv.conf file..  [done]
[14:59:57] Stopping tor service  [done]
[14:59:57] Starting new tor daemon  [done]
[14:59:57] setting up iptables rules [done]
[14:59:57] Fetching current IP...

On a second terminal, while torghost is stuck, I can't resolve domains and/or reach the internet until I stop torghost. 
Thank you.

**Comment by merkleID** [comment]
I think I found the problem: it's not able to start tor.

root@docker# journalctl -xe -f

Feb 24 16:07:39 docker sudo[6172]:     root : TTY=pts/2 ; PWD=/root/git/torghost/dist ; USER=root ; COMMAND=/bin/cp /etc/resolv.conf /etc/resolv.conf.bak
Feb 24 16:07:39 docker sudo[6172]: pam_unix(sudo:session): session opened for user root by luca(uid=0)
Feb 24 16:07:39 docker sudo[6172]: pam_unix(sudo:session): session closed for user root
Feb 24 16:07:40 docker sudo[6175]:     root : TTY=pts/2 ; PWD=/root/git/torghost/dist ; USER=root ; COMMAND=/bin/systemctl stop tor
Feb 24 16:07:40 docker sudo[6175]: pam_unix(sudo:session): session opened for user root by luca(uid=0)
Feb 24 16:07:40 docker sudo[6175]: pam_unix(sudo:session): session closed for user root
Feb 24 16:07:40 docker sudo[6179]:     root : TTY=pts/2 ; PWD=/root/git/torghost/dist ; USER=root ; COMMAND=/bin/fuser -k 9051/tcp
Feb 24 16:07:40 docker sudo[6179]: pam_unix(sudo:session): session opened for user root by luca(uid=0)
Feb 24 16:07:40 docker sudo[6179]: pam_unix(sudo:session): session closed for user root
Feb 24 16:07:40 docker sudo[6182]:     root : TTY=pts/2 ; PWD=/root/git/torghost/dist ; USER=debian-tor ; COMMAND=/usr/sbin/tor -f /etc/tor/torghostrc
Feb 24 16:07:40 docker sudo[6182]: pam_unix(sudo:session): session opened for user debian-tor by luca(uid=0)
Feb 24 16:07:40 docker sudo[6182]: pam_unix(sudo:session): session closed for user debian-tor

that's why torghost is stuck trying to fetch external IP address.

thanks.

**Comment by SusmithKrishnan** [comment]
A new kali update is causing this problem. The new permission policies is the culprit. Please check the new latest PR. Hope it works

**Comment by merkleID** [comment]
but it's not on Kali, this a ubuntu 18.04.4 host, and torghost is built from source.
