### ISSUE TITLE
Nslookup returning NXDOMAIN for everything when TORGhost on

### ISSUE THREAD

**Issue by BrunoMCBraga** [SusmithKrishnan/torghost#67]
I am unable to resolve hosts using NSlookup when torghost is being used. Is this by design?

Thanks

**Comment by SusmithKrishnan** [comment]
any unsafe connection is blocked by default. even ICMP ping is blocked
[https://superuser.com/questions/341946/can-i-ping-send-icmp-through-tor](url)
