### ISSUE TITLE
Update cannot create regular file: Text file busy

### ISSUE THREAD

**Issue by KoZmicKali** [SusmithKrishnan/torghost#71]
torghost -u
[08:24:08] Checking for update...
[08:24:10] New update available
Would you like to download latest version and build from Git repo? [Y/n]y
Cloning into 'torghost'...
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 194 (delta 56), reused 49 (delta 21), pack-reused 86
Receiving objects: 100% (194/194), 52.98 KiB | 133.00 KiB/s, done.
Resolving deltas: 100% (103/103), done.
Torghost installer v3.0
Installing prerequisites 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (18.1-5).
tor is already the newest version (0.4.2.7-1).
The following packages were automatically installed and are no longer required:
  hwdata libproj15 python3-entrypoints python3-jeepney python3-keyring python3-keyrings.alt python3-secretstorage
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing dependencies 
Requirement already satisfied: stem==1.7.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (1.7.1)
Requirement already satisfied: PyInstaller>=3.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (3.6)
Requirement already satisfied: requests==2.22.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (2.22.0)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from PyInstaller>=3.6->-r requirements.txt (line 2)) (44.0.0)
Requirement already satisfied: dis3 in /usr/local/lib/python2.7/dist-packages (from PyInstaller>=3.6->-r requirements.txt (line 2)) (0.1.3)
Requirement already satisfied: altgraph in /usr/local/lib/python2.7/dist-packages (from PyInstaller>=3.6->-r requirements.txt (line 2)) (0.17)
336 INFO: PyInstaller: 3.6
336 INFO: Python: 2.7.17
363 INFO: Platform: Linux-5.4.0-kali4-amd64-x86_64-with-debian-kali-rolling
363 INFO: wrote /tmp/torghost/torghost.spec
444 INFO: UPX is available.
460 INFO: Extending PYTHONPATH with paths
['/tmp/torghost', '/tmp/torghost']
460 INFO: checking Analysis
460 INFO: Building Analysis because Analysis-00.toc is non existent
460 INFO: Initializing module dependency graph...
464 INFO: Caching module graph hooks...
504 INFO: Caching module dependency graph...
533 INFO: running Analysis Analysis-00.toc
582 INFO: Analyzing /tmp/torghost/torghost.py
3343 INFO: Processing pre-safe import module hook   six.moves
11184 INFO: Processing pre-safe import module hook   _xmlplus
13382 INFO: Processing module hooks...
13383 INFO: Loading module hook "hook-xml.py"...
13549 INFO: Loading module hook "hook-sqlite3.py"...
13661 INFO: Loading module hook "hook-encodings.py"...
14463 INFO: Loading module hook "hook-httplib.py"...
14473 INFO: Loading module hook "hook-certifi.py"...
14484 INFO: Loading module hook "hook-cryptography.py"...
14746 INFO: Looking for ctypes DLLs
14794 INFO: Analyzing run-time hooks ...
14803 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
14838 INFO: Including run-time hook 'pyi_rth_certifi.py'
14858 INFO: Looking for dynamic libraries
15624 INFO: Looking for eggs
15624 INFO: Python library not in binary dependencies. Doing additional searching...
15719 INFO: Using Python library /lib/x86_64-linux-gnu/libpython2.7.so.1.0
15732 INFO: Warnings written to /tmp/torghost/build/torghost/warn-torghost.txt
15817 INFO: Graph cross-reference written to /tmp/torghost/build/torghost/xref-torghost.html
16013 INFO: checking PYZ
16013 INFO: Building PYZ because PYZ-00.toc is non existent
16013 INFO: Building PYZ (ZlibArchive) /tmp/torghost/build/torghost/PYZ-00.pyz
16820 INFO: Building PYZ (ZlibArchive) /tmp/torghost/build/torghost/PYZ-00.pyz completed successfully.
16946 INFO: checking PKG
16946 INFO: Building PKG because PKG-00.toc is non existent
16946 INFO: Building PKG (CArchive) PKG-00.pkg
21309 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
21332 INFO: Bootloader /usr/local/lib/python2.7/dist-packages/PyInstaller/bootloader/Linux-64bit/run
21332 INFO: checking EXE
21333 INFO: Building EXE because EXE-00.toc is non existent
21333 INFO: Building EXE from EXE-00.toc
21355 INFO: Appending archive to ELF section in EXE /tmp/torghost/dist/torghost
21458 INFO: Building EXE from EXE-00.toc completed successfully.
cp: cannot create regular file '/usr/bin/torghost': Text file busy

**Comment by VP-TBY** [comment]
torghost-u and do not say yes or enter,
then go to file (usr/bin/torghost) and delete,
than back to terminal and say yes.

**Comment by KoZmicKali** [comment]
> torghost-u and do not say yes or enter,
> then go to file (usr/bin/torghost) and delete,
> than back to terminal and say yes.

Thanks
