### ISSUE TITLE
this needs a status check command

### ISSUE THREAD

**Issue by ahb-dev** [SusmithKrishnan/torghost#73]
ive ran into a couple permission errors and the like because there is no way to check status without changing ip or restarting the service a torghost --status would be super helpfull

**Comment by NandanDesai** [comment]
I forked this project and created [this](https://github.com/databurn-in/TorGhost). There, I have added `torghost -i` which gives you the status of Tor and the IP address, if that was what you were looking for...

**Comment by SusmithKrishnan** [comment]
Check the latest update!
