### ISSUE TITLE
Syntax Error?

### ISSUE THREAD

**Issue by phaedonv** [SusmithKrishnan/torghost#76]
torghost/torghost.py", line 38
     print "User interrupt ! shutting down"
           ^
 SyntaxError: Missing parentheses in call to 'print'. Did you mean print("User interrupt ! shutting down")?

cp: cannot stat 'dist/torghost': No such file or directory

# I get this, in terminal after I run ./build.sh..!

**Comment by SkyBoltDom** [comment]
Just run install.sh. Why would you need to individually build it?

**Comment by SkyBoltDom** [comment]
The problem is, the directory it is pulling from does not exist because install.sh has not built it yet.
