### ISSUE TITLE
how to uninstall torghost?

### ISSUE THREAD

**Issue by azamet90** [SusmithKrishnan/torghost#81]
how to uninstall this completely? its not working good i did not like it

**Comment by Fairen** [comment]
First remove the git folder, then remove the link : 
`sudo rm -rf /usr/bin/torghost`

**Comment by SkyBoltDom** [comment]
It is probably something on your side because it is a beautifully effective program and is perfect for my use on Kali linux.

**Comment by azamet90** [comment]
> It is probably something on your side because it is a beautifully effective program and is perfect for my use on Kali linux.

i think there is better tools like anonsurf for example

**Comment by SusmithKrishnan** [comment]
Torghost is nothing but a simple IP tables loading script.  Anon Surf has some other features. feel free to use that if it suits your need.
