### ISSUE TITLE
raw_input is not defined Error

### ISSUE THREAD

**Issue by Noor-Kalibbala** [SusmithKrishnan/torghost#87]
in the torghost.py file there is python 2 raw_input syntax which fails

**Comment by rooteeed** [comment]
same problem please help

**Comment by Noor-Kalibbala** [comment]
Actually I changed that syntax to input and even in some exception block I
have to change it into Python3 syntax after cloning from the github then u
run the following commends of build and changing rights. Everything worked
fine.

And also if u can run torghost.py file after changing that syntax in the
terminal like Python torghost.py -s
It also worked

**Comment by SusmithKrishnan** [comment]
Fixed!
